# Generated by Django 3.1.1 on 2020-09-04 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0002_todoitem_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='post_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='post_date',
            new_name='created',
        ),
    ]
