# Generated by Django 3.1.1 on 2020-09-10 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0003_auto_20200904_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='desc',
            new_name='title',
        ),
    ]
