# Generated by Django 3.1.1 on 2020-09-10 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0005_auto_20200910_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='done',
            new_name='completed',
        ),
    ]
